apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mqtt-filtering

resources:
  - namespace.yaml
  - configmaps.yaml
  - mosquitto-deployment.yaml
  - generator-deployment.yaml
  - keyword-filter-deployment.yaml
  - url-inspector-deployment.yaml
  - format-checker-deployment.yaml
  - aggregator-deployment.yaml
  - final-router-deployment.yaml
  - ui-dashboard-deployment.yaml

